### ISSUE TITLE
Zpl format

### ISSUE THREAD

**Issue by el07694** [jcheng31/Zunify#1]
[playlist.zip](https://github.com/jcheng31/Zunify/files/4557131/playlist.zip)

I attached a .zpl file saved from Zoom player in Windows 10.

As you can see there is difference between zpl files.

Can you advised me about the subject?

**Comment by jcheng31** [comment]
Hey - the ZPL files this project deals with are those generated by the (now-defunct) Microsoft Zune software; it's not designed to handle files from Zoom Player.

**Comment by el07694** [comment]
Microsoft Zune player is a software available only for Windows phones?
